---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipsvc
  name: ipsvc
spec:
  selector:
    app: ipsvc
  type: NodePort
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
